# Generated by Django 2.2.13 on 2022-02-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='article_category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
    ]
