# Generated by Django 2.2.13 on 2022-02-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220218_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='article_publisher',
        ),
    ]
